name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Run Test for Hadoop image
      - name: Build the Haboop image
        run: docker build . --file ./build/docker/hadoop/Dockerfile  --tag hadoop:latest$(date +%s)
      # Run for Spark image
      - name: Build the Spark image
        run: docker build . --file ./build/docker/spark/base/Dockerfile  --tag my-image-name:$(date +%s)
      # Run for spark base image
      - name: Build the Spark base image
        run: docker build . --file ./build/docker/spark/spark-base-image/Dockerfile  --tag my-image-name:$(date +%s)
      # Run for spark master image
      - name: Build the Spark master
        run: docker build . --file ./build/docker/spark/spark-master/Dockerfile  --tag my-image-name:$(date +%s)
      # Run for spark worker image
      - name: Build the Spark worker image
        run: docker build . --file ./build/docker/spark/spark-worker/Dockerfile  --tag my-image-name:$(date +%s)